worth:
  KELP:
    sell: 200
  SEA_PICKLE:
    sell: 150
  PINK_PETALS:
    sell: 125
  SHULKER_BOX:
    sell: 200
  DIAMOND_HOE:
    sell: 250
  NETHERITE_BLOCK:
    sell: 250000
  DRAGON_EGG:
    sell: 2000000
  BEACON:
    sell: 400000
  ANCIENT_DEBRIS:
    sell: 15000
  NETHERITE_SCRAP:
    sell: 12000
  NETHERITE_INGOT:
    sell: 50000
  NETHER_STAR:
    sell: 25000
  ELYTRA:
    sell: 15000
  CHEST:
    sell: 25
  OAK_CHEST_BOAT:
    sell: 50
  SPRUCE_CHEST_BOAT:
    sell: 50
  BIRCH_CHEST_BOAT:
    sell: 50
  JUNGLE_CHEST_BOAT:
    sell: 50
  ACACIA_CHEST_BOAT:
    sell: 50
  DARK_OAK_CHEST_BOAT:
    sell: 50
  MANGROVE_CHEST_BOAT:
    sell: 50
  BAMBOO_CHEST_RAFT:
    sell: 50
  CHERRY_CHEST_BOAT:
    sell: 50
  TRAPPED_CHEST:
    sell: 75
  CHEST_MINECART:
    sell: 250

money:
  starting-balance: 0

shardgainer:
  blocks-per-roll: 64
  reward-chance: 25.0
  rewards:
    1: 60
    2: 20
    3: 10
    4: 7
    5: 3
